steps:
  # set registry
  - id: set-registry
    name: node:14-slim
    entrypoint: npm
    args: [
        "config",
        "set",
        "@sonova-marketing:registry=https://npm.pkg.github.com",
      ] # set registry
    # set token
  - id: set-token
    name: node:14-slim
    entrypoint: npm
    args: ["config", "set", "//npm.pkg.github.com/:_authToken=$_NPM_TOKEN"]
  # install dependencies
  - id: install-dependencies
    name: node:14-slim
    entrypoint: npm
    args: ["install"]
    dir: "./tests/integration/"
  # run jest
  - id: run-jest
    name: node:14-slim
    entrypoint: npm
    args: ["run", "test"]
    dir: "./tests/integration/"
